# This file is part of BOINC.
# http://boinc.berkeley.edu
# Copyright (C) 2023 University of California
#
# BOINC is free software; you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License
# as published by the Free Software Foundation,
# either version 3 of the License, or (at your option) any later version.
#
# BOINC is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with BOINC.  If not, see <http://www.gnu.org/licenses/>.

name: Windows
on:
  push:
    branches: [ master, 'client_release/**','5065-*' ]
    tags: [ 'client_release/**' ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron:  '0 0 * * 0'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  AWS_ACCESS_KEY_ID: ${{secrets.S3_ACCESS_KEY}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.S3_SECRET_KEY}}
  AWS_DEFAULT_REGION: us-west-2
  # installer certificates
  CERTIFICATE_SIGN: ${{ secrets.CERTIFICATE_FILE }}
  CERTIFICATE_PASS: ${{ secrets.CERTIFICATE_PASS }}
  # virtualbox vars here are for convenience, wix sources need to be updated also (name and guid)
  VBOX_URL: https://download.virtualbox.org/virtualbox/7.0.10/VirtualBox-7.0.10-158379-Win.exe
  VBOX_NAME: VirtualBox-7.0.10-158379-Win.exe
  VBOX_MD5: 8882a55227cccc8a3f7ab69641df19fd # keep lowercase
  
  
jobs:
  build:
    name: ${{matrix.configuration}}-${{matrix.platform}}-${{matrix.type}}
    runs-on: windows-2022
    strategy:
      matrix:
        type: [libs-cmake, msbuild]
        platform: [x64, ARM64]
        configuration: [Release]
      fail-fast: false
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Download OpenCppCoverage
        uses: suisei-cn/actions-download-file@v1
        if: success() && matrix.platform == 'x64'
        id: DownloadOpenCppCoverage
        with:
          url: "https://opencppcoverage.gallerycdn.vsassets.io/extensions/opencppcoverage/opencppcoverageplugin/0.9.7.1/1581265346391/OpenCppCoverage-0.9.7.1.vsix"
          target: ${{github.workspace}}\temp\

      - name: Unzip OpenCppCoverage
        if: success() && matrix.platform == 'x64'
        uses: DuckSoft/extract-7z-action@v1.0
        with:
          pathSource: ${{github.workspace}}\temp\OpenCppCoverage-0.9.7.1.vsix
          pathTarget: ${{github.workspace}}\temp\OpenCppCoverage

      - name: Setup msbuild
        uses: microsoft/setup-msbuild@v1

      - name: Check if build is running from origin repo
        if: ${{success() && env.AWS_ACCESS_KEY_ID != 0 && env.AWS_SECRET_ACCESS_KEY != 0}}
        run: |
          echo "VCPKG_BINARY_SOURCES=clear;x-aws,s3://vcpkg.cache.boinc/,readwrite" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append

      - name: Check if build is running from fork
        if: ${{success() && (env.AWS_ACCESS_KEY_ID == 0 || env.AWS_SECRET_ACCESS_KEY == 0)}}
        run: |
          echo "VCPKG_BINARY_SOURCES=clear;x-aws-config,no-sign-request;x-aws,s3://vcpkg.cache.boinc/,read" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append

      - name: Fix vcpkg
        run: vcpkg.exe integrate remove

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ${{github.workspace}}\3rdParty\Windows\cuda\
          key: windows-${{matrix.platform}}-${{matrix.configuration}}-${{hashFiles('win_build/vcpkg_3rdparty_dependencies.vcxproj', '.github/workflows/windows.yml')}}

      - name: Build
        if: success() && matrix.type == 'msbuild'
        run: msbuild win_build\boinc.sln -p:Configuration=${{matrix.configuration}} -p:Platform=${{matrix.platform}} -p:VcpkgTripletConfig=ci -m

      - name: Build CMake
        if: success() && matrix.type == 'libs-cmake'
        run: windows\ci_build_libs_cmake.bat ${{matrix.platform}} ${{matrix.configuration}}

      - name: Run tests
        if: success() && matrix.platform == 'x64' && matrix.type == 'msbuild'
        working-directory: win_build\Build\${{matrix.platform}}\${{matrix.configuration}}
        run: ${{github.workspace}}\temp\OpenCppCoverage\OpenCppCoverage-x64\OpenCppCoverage.exe --cover_children --optimized_build --sources ${{github.workspace}} --export_type=cobertura:cobertura.xml -- unittests.exe --gtest_output=xml:gtest.xml

      - name: Prepare logs on failure
        if: ${{failure()}}
        run: |
          python ./deploy/prepare_deployment.py logs

      - name: Upload logs on failure
        if: ${{failure()}}
        uses: actions/upload-artifact@v3
        with:
          name: windows_logs_${{matrix.type}}_${{github.event.pull_request.head.sha}}
          path: deploy/logs.7z

      - name: Prepare artifacts for deploy
        if: success() && matrix.type == 'msbuild'
        shell: cmd
        run: |
          python deploy\prepare_deployment.py win_apps
          python deploy\prepare_deployment.py win_client
          python deploy\prepare_deployment.py win_manager

      - name: Upload apps
        if: success() && matrix.type == 'msbuild'
        uses: actions/upload-artifact@v3
        with:
          name: win_apps_${{matrix.platform}}_${{github.event.pull_request.head.sha}}
          path: deploy/win_apps.7z

      - name: Upload client
        if: success() && matrix.type == 'msbuild'
        uses: actions/upload-artifact@v3
        with:
          name: win_client_${{matrix.platform}}_${{github.event.pull_request.head.sha}}
          path: deploy/win_client.7z

      - name: Upload manager
        if: success() && matrix.type == 'msbuild'
        uses: actions/upload-artifact@v3
        with:
          name: win_manager_${{matrix.platform}}_${{github.event.pull_request.head.sha}}
          path: deploy/win_manager.7z

      - name: Upload symbol files
        if: success() && matrix.type == 'msbuild'
        uses: actions/upload-artifact@v3
        with:
          name: win_pdb_${{matrix.platform}}_${{github.event.pull_request.head.sha}}
          path: win_build/Build/${{matrix.platform}}/${{matrix.configuration}}/*.pdb

      - name: Upload Google Tests Results
        if: always() && matrix.platform == 'x64' && matrix.type == 'msbuild'
        uses: actions/upload-artifact@v3
        with:
          name: Windows_tests_results
          path: "win_build/Build/${{matrix.platform}}/${{matrix.configuration}}/**/gtest.xml"

      - name: Upload coverage report
        if: success() && matrix.platform == 'x64' && matrix.type == 'msbuild'
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
          verbose: false

  build-installers:
    name: Installers
    runs-on: windows-2022
    needs: build
    strategy:
      matrix:
        arch: ['x64','arm64']
        variant: [ '', 'vbox' ]
        exclude:
          - arch: arm64
            variant: vbox
      fail-fast: false
    defaults:
      run:
        shell: pwsh   # necessary for installer script
    env:
      PREREQUISITES_PATH: "${{ github.workspace }}\\build\\prerequisites"
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Extract version
        id: boinc-version-extract
        run: |
          $env:BOINC_VER = '<undefined>'
          try {
            $version = (type version.h | Select-String "#define BOINC_VERSION_STRING `"(.+)`"").Matches.Groups[1].Value
            $env:BOINC_VER = $version
            $versionVariable = "boincVersionString={0}" -f $version
            echo $versionVariable | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
          }
          catch {
            throw "Failed to extract BOINC version!"
          }

      - name: Install Wix
        uses: actions/checkout@v2
        with:
          repository: parvit/wix
          path: wix

      - name: Install MSBuild
        uses: microsoft/setup-msbuild@v1.1
        with:
            vs-version: '[17.0,19)'

      - name: Create build folders
        run: |
          New-Item -Path "${{ github.workspace }}\build" -ItemType directory
          New-Item -Path "${{ github.workspace }}\build\prerequisites" -ItemType directory

      - name: Restore cached VirtualBox installer
        if: ${{ matrix.variant == 'vbox' }}
        id: cache-vbox-restore
        uses: actions/cache/restore@v3
        with:
          path: "${{ env.PREREQUISITES_PATH }}\\${{ env.VBOX_NAME }}"
          key: ${{ env.VBOX_NAME }}-${{ env.VBOX_MD5 }}

      - name: Download prerequisite VirtualBox if needed
        if: ${{ matrix.variant == 'vbox' && steps.cache-vbox-restore.outputs.cache-hit != 'true' }}
        run: |
          # Download Virtualbox prerequisite
          Invoke-WebRequest -Uri "${{ env.VBOX_URL }}" -TimeoutSec 60 -OutFile "${{ env.PREREQUISITES_PATH }}\\${{ env.VBOX_NAME }}"
          $md5 = (Get-FileHash "${{ env.PREREQUISITES_PATH }}\\${{ env.VBOX_NAME }}" -Algorithm MD5).Hash.ToLower()
          if ( !($md5 -eq "${{ env.VBOX_MD5 }}") ) {
            throw "VirtualBox installer download failed"
          }

      - name: Save prerequisite VirtualBox if needed
        if: ${{ matrix.variant == 'vbox' && steps.cache-vbox-restore.outputs.cache-hit != 'true' }}
        uses: actions/cache/save@v3
        with:
          path: "${{ env.PREREQUISITES_PATH }}\\${{ env.VBOX_NAME }}"
          key: ${{ env.VBOX_NAME }}-${{ env.VBOX_MD5 }}

      - name: Download Client Artifact
        if: ${{ success() }}
        uses: actions/download-artifact@v3
        with:
          name: win_client_${{ matrix.arch }}_${{github.event.pull_request.head.sha}}
          path: pkgs/

      - name: Download Manager Artifact
        if: ${{ success() }}
        uses: actions/download-artifact@v3
        with:
          name: win_manager_${{ matrix.arch }}_${{github.event.pull_request.head.sha}}
          path: pkgs/

      - name: Decompress Artifacts
        if: ${{ success() }}
        run: |
          pushd "${{ github.workspace }}\build"
          7z x "${{ github.workspace }}\pkgs\win_client.7z"
          7z x "${{ github.workspace }}\pkgs\win_manager.7z"

      - name: Build installer
        if: ${{ success() && matrix.variant != '' }}
        run: |
          $env:PATH = "${{ github.workspace }}\wix\bin\;" + $env:PATH
          $env:WIX = "${{ github.workspace }}\wix\bin\"
          pwsh -noninteractive -f .\installer.ps1 -Type "${{ matrix.arch }}_${{ matrix.variant }}" `
               -Version "${{ steps.boinc-version-extract.outputs.boincVersionString }}" `
               -CI -Certificate "${{ github.workspace }}\${{env.CERTIFICATE_SIGN}}" `
               -CertificatePass "${{ env.CERTIFICATE_PASS }}"

      - name: Build installer
        if: ${{ success() && matrix.variant == '' }}
        run: |
          $env:PATH = "${{ github.workspace }}\wix\bin\;" + $env:PATH
          $env:WIX = "${{ github.workspace }}\wix\bin\"
          pwsh -noninteractive -f .\installer.ps1 -Type "${{ matrix.arch }}" `
               -Version "${{ steps.boinc-version-extract.outputs.boincVersionString }}" `
               -CI -Certificate "${{ github.workspace }}\${{env.CERTIFICATE_SIGN}}" `
               -CertificatePass "${{ env.CERTIFICATE_PASS }}"

      - name: Upload installer
        if: ${{ success() }}
        uses: actions/upload-artifact@v3
        with:
          name: boinc_bundle_${{ steps.boinc-version-extract.outputs.boincVersionString }}_${{ matrix.variant }}_${{ matrix.arch }}_${{github.event.pull_request.head.sha}}
          path: build/*_windows_*.exe
